'use client';

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { NuqsAdapter } from 'nuqs/adapters/next/app'
import { Toaster } from "@/components/ui/sonner"
import "./globals.css";
import { useEffect } from "react";
import useWishlistStore from "@/lib/store/useWishlistStore";
import { authClient } from "@/lib/auth-client";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Reals Demo v1",
//   description: "Your Ai Date Planner Generated by Reals",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { data: session, isPending } = authClient.useSession()// or however you get session
  const hydrate = useWishlistStore((s) => s.hydrate);

  useEffect(() => {
    // Only hydrate when:
    // - Session exists (user logged in)
    // - Not loading
    // - Hydration hasn't run yet (store handles this internally)
    if (session?.user && !isPending) {
      hydrate();
    }
  }, [session, isPending, hydrate]);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <NuqsAdapter>

          {children}

          <Toaster />
        </NuqsAdapter>

      </body>
    </html>
  );
}
